export const username = '//input[@name="login[username]"]'
export const password = '//input[@name="login[password]"]'
export const loginbutton = '(//button[@type="submit"])[2]'
export const option = '(//button[@class="action switch"])[1]'
export const signoff = '(//li[@class="authorization-link"])[1]'